### Endpoint inicial
GET http://localhost:5000

### Endpoint para convertir yt a texto
POST http://localhost:5000/convert
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=cz-DaqClllQ"
}